module.exports = {
  COMMUNITY_CHAT: "COMMUNITY_CHAT",
  USER_CONNECTED: "USER_CONNECTED",
  MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
  MESSSAGE_SENT: "MESSSAGE_SENT",
  USER_DISCONNECTED: "USER_DISCONNECTED",
  TYPING: "TYPING",
  VERIFY_USERNAME: "VERIFY_USERNAME",
  USER_LOGOUT: "USER_LOGOUT"
};
